CREATE TABLE esbuser.bck_roles
(
    id           int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_name    varchar(255) DEFAULT NULL,
    date_created timestamp    DEFAULT NULL,
    created_by   varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE esbuser.bck_rev_users
(
    id              int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    firstname       varchar(40)  DEFAULT NULL,
    lastname        varchar(40)  DEFAULT NULL,
    email           varchar(50) NOT NULL,
    role_id         int          DEFAULT NULL,
    date_created    timestamp    DEFAULT NULL,
    date_modified   timestamp    DEFAULT NULL,
    last_login_date timestamp    DEFAULT NULL,
    login_ip        varchar(30)  DEFAULT NULL,
    modified_by     varchar(255) DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT rev_users_ibfk_1 FOREIGN KEY (role_id) REFERENCES esbuser.bck_roles (id)
);

CREATE TABLE esbuser.bck_permissions
(
    id              int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    permission_name varchar(255) DEFAULT NULL,
    uuid            varchar(255) DEFAULT NULL,
    date_created    timestamp    DEFAULT NULL,
    created_by      varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE esbuser.bck_role_permission
(
    id            int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_id       int NOT NULL,
    permission_id int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (permission_id) REFERENCES esbuser.bck_permissions (id),
    FOREIGN KEY (role_id) REFERENCES esbuser.bck_roles (id)
);

CREATE TABLE esbuser.channel_audit
(
    id                int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APPL_CODE         varchar(20) DEFAULT NULL,
    APPL_NAME         varchar(20) DEFAULT NULL,
    ENTRY_DATE        timestamp,
    ENTERED_BY        varchar(40) DEFAULT NULL,
    AUTH_FLG          varchar(2)  DEFAULT 'Y',
    AUTH_DATE         timestamp   DEFAULT NULL,
    AUTH_BY           varchar(40) DEFAULT NULL,
    VENDING_AGGR_CODE varchar(20),
    LAST_SWITCH_DATE  TIMESTAMP,
    FAILURE_THRESHOLD INT         DEFAULT 10,
    NUMBER_OF_MINUTES INT         DEFAULT 10,
    DATA_AGGR_CODE    VARCHAR(20) DEFAULT NULL,
    DEL_FLG           VARCHAR(2)  DEFAULT 'N',
    DEL_DATE          TIMESTAMP   DEFAULT sysdate,
    DEL_BY            VARCHAR(40) DEFAULT NULL,
    ACTION            VARCHAR(40) NOT NULL,
    ACTION_ID         VARCHAR(40) NOT NULL

);

CREATE TABLE esbuser.channel_aux
(
    id                int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APPL_CODE         varchar(20) DEFAULT NULL,
    APPL_NAME         varchar(20) DEFAULT NULL,
    ENTRY_DATE        timestamp,
    ENTERED_BY        varchar(40) DEFAULT NULL,
    AUTH_FLG          varchar(2)  DEFAULT 'Y',
    AUTH_DATE         timestamp   DEFAULT NULL,
    AUTH_BY           varchar(40) DEFAULT NULL,
    VENDING_AGGR_CODE varchar(20),
    LAST_SWITCH_DATE  TIMESTAMP,
    FAILURE_THRESHOLD INT         DEFAULT 10,
    NUMBER_OF_MINUTES INT         DEFAULT 10,
    DATA_AGGR_CODE    VARCHAR(20) DEFAULT NULL,
    DEL_FLG           VARCHAR(2)  DEFAULT 'N',
    DEL_DATE          TIMESTAMP   DEFAULT sysdate,
    DEL_BY            VARCHAR(40) DEFAULT NULL,
    DEACTIVATION_FLG  varchar(2) NOT NULL,
    APPROVAL_FLG      varchar(2) NOT NULL,


)
CREATE TABLE esbuser.app_audit
(
    id int GENERATED BY DEFAULT ON NULL AS IDENTITY,

)

CREATE TABLE esbuser.aggregator_audit
(
    id int GENERATED BY DEFAULT ON NULL AS IDENTITY,

) INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('GUEST', sysdate, 'system', 'SUPPORT');
INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('INITIATOR', sysdate, 'system', 'SUPPORT');
INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('APPROVER', sysdate, 'system', 'SUPPORT');
INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('ADMIN', sysdate, 'system', 'SUPPORT');

INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code)
VALUES ('READ', NULL, sysdate, 'system', 'SUPPORT');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by, app_code)
VALUES ('INITIATE_REQUEST', NULL, sysdate, 'system', 'SUPPORT');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by, app_code)
VALUES ('APPROVE_SUBS', NULL, sysdate, 'system', 'SUPPORT');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by, app_code)
VALUES ('CREATE_SUBS', NULL, sysdate, 'system', 'SUPPORT');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by, app_code)
VALUES ('CREATE_USER', NULL, sysdate, 'system', 'SUPPORT');

INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code);)
VALUES (1, 'READ', NULL, sysdate, 'system', 'SUPPORT' );
INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code);)
VALUES (2, 'CREATE', NULL, sysdate, 'system', 'SUPPORT' );
INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code);)
VALUES (3, 'APPROVE', NULL, sysdate, 'system', 'SUPPORT' );
INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code);)
VALUES (4, 'MODIFY-USERS', NULL, sysdate, 'system', 'SUPPORT' );

INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (9, 1, 1, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (10, 2, 1, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (11, 3, 1, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (12, 4, 1, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (13, 2, 2, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (14, 3, 2, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (15, 4, 2, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (16, 3, 3, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (17, 4, 3, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (18, 2, 4, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (19, 3, 4, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (20, 4, 4, 'SUPPORT' );
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (21, 4, 5, 'SUPPORT' );

INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (9, 1, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (10, 5, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (11, 6, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (12, 7, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (13, 5, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (14, 6, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (15, 7, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (16, 6, 3);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (17, 7, 3);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (18, 5, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (19, 6, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (20, 7, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (21, 7, 5);

UPDATE esbuser.bck_roles
SET id = 1
where id = 5;
UPDATE esbuser.bck_roles
SET id = 2
where id = 6;
UPDATE esbuser.bck_roles
SET id = 3
where id = 7;
UPDATE esbuser.bck_roles
SET id = 4
where id = 8;

create table esbuser.switch_resources
(
    id     number generated by default on null as identity,
    method varchar2(10),
    url    varchar2(75),
    constraint unq_swtch_resc UNIQUE (method, url)
);
INSERT INTO esbuser.switch_resources(id, method, url)
values (1, 'GET', '/switch/getusers');
INSERT INTO esbuser.switch_resources(id, method, url)
values (2, 'GET', '/switch/getroles');
INSERT INTO esbuser.switch_resources(id, method, url)
values (3, 'POST', '/switch/updateuserrole');
INSERT INTO esbuser.switch_resources(id, method, url)
values (4, 'GET', '/switch/switch');
INSERT INTO esbuser.switch_resources(id, method, url)
values (5, 'POST', '/switch/switch');
INSERT INTO esbuser.switch_resources(id, method, url)
values (6, 'PUT', '/switch/switch');
INSERT INTO esbuser.switch_resources(id, method, url)
values (7, 'POST', '/switch/approve-switch');
INSERT INTO esbuser.switch_resources(id, method, url)
values (8, 'GET', '/switch/endpoint');
INSERT INTO esbuser.switch_resources(id, method, url)
values (9, 'POST', '/switch/endpoint');
INSERT INTO esbuser.switch_resources(id, method, url)
values (10, 'PUT', '/switch/endpoint');
INSERT INTO esbuser.switch_resources(id, method, url)
values (11, 'POST', '/switch/approve-endpoint');
INSERT INTO esbuser.switch_resources(id, method, url)
values (12, 'GET', '/switch/perf-stat');
INSERT INTO esbuser.switch_resources(id, method, url)
values (13, 'GET', '/switch/transactions');
INSERT INTO esbuser.switch_resources(id, method, url)
values (14, 'GET', '/switch/uploadfile');
INSERT INTO esbuser.switch_resources(id, method, url)
values (15, 'POST', '/switch/uploadfile');
INSERT INTO esbuser.switch_resources(id, method, url)
values (16, 'PUT', '/switch/uploadfile');
INSERT INTO esbuser.switch_resources(id, method, url)
values (17, 'POST', '/switch/uploadfile/approve');

create table esbuser.switch_permission_resources
(
    id            number generated by default on null as identity,
    permission_id number,
    resources_id  number,
    constraint unq_swtch_perm_resc UNIQUE (permission_id, resources_id)
);

INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (1, 1, 4);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (2, 2, 4);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (3, 3, 4);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (4, 4, 1);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (5, 5, 2);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (6, 6, 2);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (7, 7, 3);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (8, 8, 1);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (9, 9, 2);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (10, 10, 2);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (11, 11, 3);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (12, 12, 1);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (13, 13, 1);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (14, 14, 1);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (15, 15, 2);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (16, 16, 2);
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id)
values (17, 17, 3);

INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (1, 1, 1, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (2, 2, 1, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (3, 3, 1, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (4, 4, 1, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (5, 2, 2, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (6, 3, 2, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (7, 4, 2, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (8, 3, 3, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (9, 4, 3, 'SUPPORT');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (10, 4, 4, 'SUPPORT');

INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (1, 'GET', '/support/getusers', 'SUPPORT' );
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (2, 'GET', '/support/getroles', 'SUPPORT' );
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (3, 'POST', '/support/updateuserrole', 'SUPPORT' );


INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (1, 1, 4, 'SUPPORT' );
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (2, 2, 4, 'SUPPORT' );
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (3, 3, 4, 'SUPPORT' );


