package constants;

public enum ModuleName {
    EXCEP_REV, STAND_REV, FUNDS_RECOUP, UNSETTLED_TRXN, SETTLEMENT_REPORT,
    INTER_BANK_BULK_PAYMENT_SUMMARY, INTRA_BANK_BULK_PAYMENT_SUMMARY, INTER_BANK_BULK_PAYMENT_DETAILS,
    INTRA_BANK_BULK_PAYMENT_DETAILS
}
